/**
 * Frontend Zoho service — thin proxy over the backend API.
 *
 * ALL token management, token refresh, and Zoho API calls are handled
 * by the Express backend (server/routes/zoho.js + server/services/zohoService.js).
 *
 * The frontend never touches Zoho tokens directly. This avoids:
 *   - CORS errors (Zoho token endpoint doesn't allow browser requests)
 *   - Token leakage (access/refresh tokens stay on the server)
 *   - Firebase Realtime Database dependency (fully removed)
 */

import { API_ENDPOINTS } from '../utils/apiConfig';
import { getAccessToken } from './supabase';

// ── Helpers ──────────────────────────────────────────────────────────────────

async function authHeaders(): Promise<Record<string, string>> {
  const token = await getAccessToken();
  return token ? { Authorization: `Bearer ${token}` } : {};
}

// ── ZohoService ───────────────────────────────────────────────────────────────

export class ZohoService {
  /**
   * Always configured — credentials are verified per-org by the backend.
   */
  static isConfigured(): boolean {
    return true;
  }

  /**
   * OAuth URL is generated by the backend.
   * Callers should use API_ENDPOINTS.zohoAuthUrl instead.
   */
  static getAuthUrl(_organizationId: string, _userId: string): string {
    throw new Error('Use API_ENDPOINTS.zohoAuthUrl and fetch the auth URL from the backend.');
  }

  /**
   * Token exchange is handled by the backend callback route.
   */
  static async exchangeCodeForTokens(
    _code: string,
    _state: string,
  ): Promise<never> {
    throw new Error('Token exchange is handled by the backend. Use /api/zoho/auth/callback.');
  }

  /**
   * Token refresh is automatic on the backend — no frontend action needed.
   * This stub exists for any legacy callers.
   */
  static async refreshAccessToken(_refreshToken: string): Promise<never> {
    throw new Error('Token refresh is handled automatically by the backend.');
  }

  /**
   * Returns true when the org has a valid Zoho connection (tokens on file).
   * Checks via GET /api/zoho/config — does NOT expose the token to the browser.
   */
  static async isConnected(organizationId: string): Promise<boolean> {
    try {
      const headers = await authHeaders();
      const res = await fetch(
        `${API_ENDPOINTS.zohoConfig}?orgId=${encodeURIComponent(organizationId)}`,
        { headers },
      );
      if (!res.ok) return false;
      const data = await res.json();
      return data.configured === true;
    } catch {
      return false;
    }
  }

  /**
   * Import all Zoho Books items into Supabase.
   * Calls POST /api/zoho/import — backend fetches, transforms, and upserts.
   * Token refresh is automatic; no manual reconnect unless the refresh_token is revoked.
   */
  static async importItems(organizationId: string): Promise<any[]> {
    const headers = await authHeaders();
    const res = await fetch(API_ENDPOINTS.zohoImport(organizationId), {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...headers },
    });
    const data = await res.json();
    if (res.status === 401) {
      throw new Error(data.message || 'Zoho access token expired. Please reconnect Zoho Books.');
    }
    if (!res.ok || !data.success) {
      throw new Error(data.message || `Zoho import failed: HTTP ${res.status}`);
    }
    // Return items array with summary metadata
    const result: any[] = [];
    result._importedCount = data.data.upserted;
    result._totalZoho = data.data.total;
    return result;
  }

  /**
   * Remove Zoho OAuth tokens (disconnect).
   * Calls DELETE /api/zoho/tokens — clears tokens in Supabase, keeps credentials.
   */
  static async removeTokens(organizationId: string): Promise<void> {
    const headers = await authHeaders();
    const res = await fetch(API_ENDPOINTS.zohoTokens(organizationId), {
      method: 'DELETE',
      headers,
    });
    if (!res.ok) {
      const data = await res.json().catch(() => ({}));
      throw new Error(data.message || `Failed to disconnect Zoho: HTTP ${res.status}`);
    }
  }

  /**
   * Store tokens — handled by the backend callback route.
   * This stub is kept for any legacy callers.
   */
  static async storeTokens(
    _organizationId: string,
    _userId: string,
    _tokens: unknown,
  ): Promise<void> {
    throw new Error('Token storage is handled by the backend callback route.');
  }

  /**
   * Get connection info — not exposed to the browser for security.
   * Use GET /api/zoho/config to check whether credentials are configured.
   */
  static async getConnectionInfo(_organizationId: string): Promise<null> {
    return null;
  }
}
